<?php 
	return array (
		'item/([0-9]+)' => 'item/view/$1',
		'buy/([0-9]+)' => 'item/buy/$1',
		'pay/primearea/([0-9]+)' => 'item/pay/primearea/$1',
		'pay/cryptonator/([0-9]+)' => 'item/pay/cryptonator/$1',
		'purchase/([0-9]+)' => 'item/purchase/$1',
		'callback/primearea' => 'callback/primearea',
		'callback/cryptonator' => 'callback/cryptonator',
		'^page/(.*?)$' => 'index/page/$1',
		'^admin$' => 'admin/index',
		'admin/signin' => 'admin/signin',
		'^admin/goods$' => 'admin/goods/load',
		'admin/goods/add' => 'admin/goods/add',
		'admin/goods/upload/([0-9]+)' => 'admin/goods/upload/$1',
		'admin/goods/edit/([0-9]+)' => 'admin/goods/edit/$1',
		'admin/goods/delete/([0-9]+)' => 'admin/goods/delete/$1',
		'^admin/pages$' => 'admin/pages/load',
		'admin/pages/add' => 'admin/pages/add',
		'admin/pages/edit/([0-9]+)' => 'admin/pages/edit/$1',
		'admin/pages/delete/([0-9]+)' => 'admin/pages/delete/$1',
		'admin/settings' => 'admin/settings',
		'admin/design' => 'admin/design',
		'admin/users' => 'admin/users',
	);
